Adding the Re3gistry files
OSGeo/OSGeoLive-doc pull request #621
Opened 2020-09-24 15:22 UTC by df-git

2020-09-28 15:29 UTC, cvvergara commented
@df-git 
https://travis-ci.com/github/OSGeo/OSGeoLive-doc/builds/186480701#L853
```
/home/travis/build/OSGeo/OSGeoLive-doc/build/doc/quickstart/re3gistry_quickstart.rst:69: WARNING: Title underline too short.

Introduction to the Re3gistry 2

================

/home/travis/build/OSGeo/OSGeoLive-doc/build/doc/quickstart/re3gistry_quickstart.rst:69: WARNING: Title underline too short.

Introduction to the Re3gistry 2

================

/home/travis/build/OSGeo/OSGeoLive-doc/build/doc/quickstart/re3gistry_quickstart.rst:78: WARNING: Title underline too short.

Users, roles and groups

==========

/home/travis/build/OSGeo/OSGeoLive-doc/build/doc/quickstart/re3gistry_quickstart.rst:78: WARNING: Title underline too short.

Users, roles and groups

==========

/home/travis/build/OSGeo/OSGeoLive-doc/build/doc/quickstart/re3gistry_quickstart.rst:93: WARNING: Explicit markup ends without a blank line; unexpected unindent.

```

The unexpected unindent problem is on the `.. tip::` command

How it should be:

```
.. tip::
   The tip goes indented

This is not part of the tip
```

How it is now
```
.. tip::
   The tip goes indented
This is part of the tip but its not indented

This is not part of the tip
```
I made locally the indentation and it looks like this:
![image](https://user-images.githubusercontent.com/5035290/94451546-2562d400-0174-11eb-9568-29c414dc3d24.png)
I can read that you have  (i)

I played around locally: 
![image](https://user-images.githubusercontent.com/5035290/94452699-70311b80-0175-11eb-83d2-c6cbc1377ad6.png)

to get the (i) a bit more clear
![image](https://user-images.githubusercontent.com/5035290/94451957-a15d1c00-0174-11eb-91a1-d6e4a569cd71.png)

2020-09-28 15:33 UTC, cvvergara requested changes

2020-09-28 15:33 UTC, cvvergara commented on doc/quickstart/re3gistry_quickstart.rst
> +================
Make 80 chars long preferably but at least make it at least as long as the title

2020-09-28 15:33 UTC, cvvergara commented on doc/quickstart/re3gistry_quickstart.rst
> +==========
Make 80 chars long preferably but at least make it at least as long as the title

2020-09-28 15:33 UTC, cvvergara commented on doc/quickstart/re3gistry_quickstart.rst
> +.. tip::
Fix the tip, some hints are in a comment

2020-09-28 15:36 UTC, cvvergara commented
For translations this is needed:
Add the end of this file put the required lines for re3gistry, follow the example of mapcache 
https://github.com/OSGeo/OSGeoLive-doc/blob/master/.tx/config#L759

2020-10-13 19:23 UTC, kalxas commented
Installer merged now

2020-10-20 19:58 UTC, merged