Updating the INSPIRE overview file and adding the INSPIRE screenshot
OSGeo/OSGeoLive-doc pull request #622
Opened 2020-09-24 15:25 UTC by df-git

2020-09-24 15:37 UTC, df-git commented
The checks are failing because there is a reference to the re3gistry_overview file that has just been added and it needs to be approved too.

2020-09-26 01:21 UTC, cvvergara commented
I see this one:
```
2020-09-24T15:26:31.5794726Z (line   39) broken    https://etf-validator.net - 503 Server Error: Service Temporarily Unavailable for url: https://etf-validator.net/
```
here:
https://github.com/OSGeo/OSGeoLive-doc/runs/1161252637?check_suite_focus=true#step:9:574

the complete section of linkcheck is:
```
ok        https://inspire.ec.europa.eu/about-inspire/563
(line   17) ok        https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32007L0002&from=EN
(line   17) redirect  https://www.iso.org - with Found to https://www.iso.org/home.html
(line   19) redirect  https://inspire.ec.europa.eu/Themes - permanently to https://inspire.ec.europa.eu/Themes/Data-Specifications/2892
(line   33) ok        https://wiki.osgeo.org/wiki/INSPIRE
(line   36) ok        https://ec.europa.eu/jrc/en
(line   39) broken    https://etf-validator.net - 503 Server Error: Service Temporarily Unavailable for url: https://etf-validator.net/
(line   66) -local-   ../sponsors_osgeo.html
(line   71) -local-   ../sponsors_osgeo.html
(line   76) -local-   ../sponsors_osgeo.html
(line   39) ok        https://inspire.ec.europa.eu/validator/about/
(line   40) ok        https://inspire-geoportal.ec.europa.eu/
(line   38) ok        https://inspire.ec.europa.eu/registry
(line   25) ok        https://inspire.ec.europa.eu/Data-Models/Data-Specifications/2892
```
This is not checked because it does not have the `http://` or `https://` so the link checker does not consider it.
```
:doc:`Re3gistry <re3gistry_overview>`

I did a double check downloading in my computer and there was no problem, so I will re-run the link tests

2020-09-26 01:26 UTC, cvvergara requested changes

2020-09-26 01:26 UTC, cvvergara commented on doc/overview/inspire_overview.rst
> +The datasets falling under the scope of the INSPIRE Directive are grouped into 34 cross-sectoral categories names `spatial data themes <https://inspire.ec.europa.eu/Themes>`__, which are defined in t
although we dont have yet set permanent redirections warnings to be marked as errors we have that plan in the future, as it means that the original page no longer exists. Can you please change
https://inspire.ec.europa.eu/Themes 
to 
https://inspire.ec.europa.eu/Themes/Data-Specifications/2892

2020-09-26 01:39 UTC, cvvergara commented
I run twice in my computer:
```
writing output... [ 22%] overview/inspire_overview                                                                                                                                                                               
ok        https://inspire.ec.europa.eu/about-inspire/563
(line   25) ok        https://inspire.ec.europa.eu/Data-Models/Data-Specifications/2892
(line   19) redirect  https://inspire.ec.europa.eu/Themes - permanently to https://inspire.ec.europa.eu/Themes/Data-Specifications/2892
(line   33) ok        https://wiki.osgeo.org/wiki/INSPIRE
(line   17) ok        https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32007L0002&from=EN
(line   17) redirect  https://www.iso.org - with Found to https://www.iso.org/home.html
(line   39) ok        https://etf-validator.net
(line   66) -local-   ../sponsors_osgeo.html
(line   71) -local-   ../sponsors_osgeo.html
(line   76) -local-   ../sponsors_osgeo.html
(line   36) ok        https://ec.europa.eu/jrc/en
(line   39) ok        https://inspire.ec.europa.eu/validator/about/
(line   40) ok        https://inspire-geoportal.ec.europa.eu/
(line   38) ok        https://inspire.ec.europa.eu/registry
```
And I dont have problems with the link, https://etf-validator.net
But all the time I ran the actions that link shows:
```
broken    https://etf-validator.net - 503 Server Error: Service Temporarily Unavailable for url: https://etf-validator.net/
```
So, its not the only case that issue happens, can you please edit this:
https://github.com/OSGeo/OSGeoLive-doc/blob/master/doc/conf.py#L266
Add the  https://etf-validator.net  link, where its at, and the error it shows.

2020-09-26 01:45 UTC, cvvergara commented on doc/overview/inspire_overview.rst
> +The datasets falling under the scope of the INSPIRE Directive are grouped into 34 cross-sectoral categories names `spatial data themes <https://inspire.ec.europa.eu/Themes>`__, which are defined in t
I dont know why this is shown 2 times

2020-09-26 01:46 UTC, cvvergara commented
A preview of how it looks
![image](https://user-images.githubusercontent.com/5035290/94327350-098ee080-ff70-11ea-9b69-b5a6cb4ad36a.png)

2020-09-28 07:05 UTC, df-git reviewed
The changes are fine

2020-09-28 13:57 UTC, cvvergara commented
@df-git there is a missing comma at the end of the line of the conf.py

2020-09-28 15:44 UTC, cvvergara commented
This PR can be merged after #621 because it references a project not yet included on the disk

2020-09-28 15:45 UTC, cvvergara approved these changes

2020-10-20 20:06 UTC, merged