Pvgenuchten add pygeoapi qs
OSGeo/OSGeoLive-doc pull request #646
Opened 2020-11-29 04:43 UTC by cvvergara

This PR contains #638 and #640 
Also updates the locale files
When merged the PR's will close automatically

2020-11-30 15:12 UTC, cvvergara commented on projects_info.csv
> +Y | pygeoapi | 0.8.0 | Y | Y | Web Services | | OGC Web Services | pygeoapi | https://pygeoapi.io/ | OSGeo_community | pygeoapi | Y
I it on the Webservices  section

2020-12-01 21:56 UTC, astroidex requested changes
Ichecked the pygeoapi documents. They look very fine. Only one OSGeoLive typo found.

2020-12-01 21:56 UTC, astroidex commented on doc/quickstart/pygeoapi_quickstart.rst
> +OSGeo Live contains a number of datasets we can use. An example is ``/var/www/html/openlayers/examples/data/geojson/countries.geojson``.
OSGeoLive not OSGeo LIve

2020-12-02 14:47 UTC, Bakaniko approved these changes

2020-12-02 14:48 UTC, cvvergara commented
Merging as the related failed link is not part of this PR

2020-12-02 14:48 UTC, merged