Initial changes to the deegree documentation for OSGeoLive15
OSGeo/OSGeoLive-doc pull request #754
Opened 2022-07-07 20:43 UTC by julianzz98

2022-07-09 23:12 UTC, cvvergara requested changes
Hi @julianzz98 
I am in charge of the technical checks.
There are some changes to be done.

2022-07-09 23:12 UTC, cvvergara commented on doc/overview/deegree_overview.rst
> -.. presentation-note
Looks like the note for the [presentation](https://osgeo.github.io/OSGeoLive-doc/en/presentation.html#/7/1) was deleted: (Press "s" and the notes will pop out in a different window)

2022-07-09 23:12 UTC, cvvergara commented on doc/overview/deegree_overview.rst
> -.. presentation-note
![image](https://user-images.githubusercontent.com/5035290/178125339-3959131f-1b89-44c7-8086-27d6b20456f4.png)

2022-07-09 23:12 UTC, cvvergara commented on doc/quickstart/deegree_quickstart.rst
>    * deegree website - Available here: https://www.deegree.org
The syntax for bullets:
The bullet is at the first column of the line.
There are no blank lines in between when the bullet is at the same level.

```
* b1
* b2
* b3

   * b3.1
   * b3.2

* b4
```

2022-07-12 19:16 UTC, cvvergara commented
TODO I will merge and fix the issues.

2022-07-12 19:19 UTC, julianzz98 commented
Hello and sorry for not responding, I am on my way to Brazil right now and can look into fixing it only next week. If you can make the changes, I would appreciate it! Greetings

2022-07-13 15:12 UTC, merged