odc docs pages add
OSGeo/OSGeoLive-doc pull request #809
Opened 2023-04-29 03:17 UTC by darkblue-b

2023-04-29 03:33 UTC, darkblue-b commented
need to add these assets ?
```

OSGEO/OSGeoLive-doc$ grep _odc doc/overview/odc_overview.rst 
@LOGO_odc@
@OSGEO_KIND_odc@
@NAME_odc@
@SCREENSHOT_odc@
**Website:** @WEB_odc@
@VMDK_odc@
@QUICKSTART_odc@

OSGEO/OSGeoLive-doc$ grep _odc doc/quickstart/odc_quickstart.rst
@LOGO_odc@
@OSGEO_KIND_odc@
@VMDK_odc@
@NAME_odc@ Quickstart
* Website: @WEB_odc@

```

2023-04-29 07:20 UTC, kalxas commented
I see most of the quickstart is about gmt, is this work in progress?

2023-05-04 20:03 UTC, cvvergara commented
> need to add these assets? 

Its not processing that new documentation
* add it to `projects_info.csv`  (all the other assets mentioned in your question)
* Once its added you will get errors because of  @SCREENSHOT_odc@
  * You need to add the file: `odc_screenshot.png` (same directory as the logo)

2023-05-05 06:04 UTC, astroidex requested changes

2023-05-05 06:04 UTC, astroidex commented on doc/quickstart/odc_quickstart.rst
> +* Support: Slack <http://slack.opendatacube.org>
link without <>

2023-05-05 06:04 UTC, astroidex commented on doc/overview/odc_overview.rst
> +**Support:** https:///
add Slack link too Slack http://slack.opendatacube.org

2023-05-26 02:05 UTC, darkblue-b commented on doc/overview/odc_overview.rst
> +**Support:** https:///
revise PR; add screenshot, alpha text

2023-05-26 17:33 UTC, cvvergara approved these changes

2023-05-26 17:35 UTC, merged